### ISSUE TITLE
bmath.where not respecting shape of input

### ISSUE THREAD

**Issue by MarkusSchwarz1980** [blond-admin/BLonD#166]
@kiliakis Currently, bmath.where does not work for multi-dimensional input, since it only returns the first row. E.g.:
```python
import numpy as np
from blond.utils import bmath as bm
a = np.arange(9).reshape(3,3)
```
The result of `b=np.where( a > 4)` is an array of shape 3x3, but `c=bm.where(a, 4)` only returns an array of shape 3, i.e. the first row of `b`.

**Comment by kiliakis** [comment]
Since `np.where()` is a very versatile function, it is impossible to capture all the possible input cases in the C++ equivalent in `bm.where()`. The original purpose of `bm.where()` was to accelerate some basic `np.where()` statements run in the main loop. 

I will have a look and see if I can extend it to cover arbitrary array shapes, and maintain good performance. Otherwise it is better if we stick with `np.where()`.

**Comment by MarkusSchwarz1980** [comment]
The solution I found this morning is to replace line 183 by `result = np.empty_like(x, dtype=np.bool)` and replace the `__getLen(x)` arguments by `x.size`. That way, the output has the same shape as the input `x`. Compared to `a>4`, `bm.where(a, 4.0)` is about 20 times faster.

However, I now noticed that the input array needs to be a floating point type. In particular, it does not work when the input array has type `int`, i.e. the result is always `False`.
